### ISSUE TITLE
Failed postinstall script

### ISSUE THREAD

**Issue by Trollol01** [distubejs/yt-dlp#1]
I'm trying to install @distube/yt-dlp plugin, but I encountered this error:

![Installation_error](https://user-images.githubusercontent.com/62749150/169103848-401ea411-44fb-4327-b52d-70d5e3028b7a.jpg)

- Plugin version: 1.0.2
- DisTube version: 2.8.18
- discord.js version: 13.7.0 
- Node.js version: 14.16.1
- Operating system: Windows 10

**Comment by pryzmian** [comment]
You can’t use plugins with DisTube v2, update to v3 so you can use plugins, another thing is that you need node v16 and above to use DisTube v3

**Comment by skick1234** [comment]
I forgot to put the above requirements in the readme. Will do it later.
